print('LOADING MAIN PLUGINS HERE')

require('plugins.barbar')
require('plugins.colors')
require('plugins.fterm')
require('plugins.fugitive')
require('plugins.harpoon')
require('plugins.nvimtree')
require('plugins.telescope')
require('plugins.treesitter')
require('plugins.undotree')
require('plugins.dapui')
require('plugins.cursorline')
require('plugins.aimodels')
require('plugins.folding')
require('plugins.tsreact')
